### PR TITLE
MS-127: Implement input component

### PR DESCRIPTION
**Pull request by julianv97**

### CODE REVIEW

**Review by sofpag — CHANGES_REQUESTED** [review]
Psychologists is not showing the actual data for  time range and day range when I use the edit function
Sessionsis not showing the actual data for  day range and result when I use the edit function

But, I am sure it not something you did

**Comment by julianv97** [comment]
> Psychologists is not showing the actual data for time range and day range when I use the edit function Sessionsis not showing the actual data for day range and result when I use the edit function
> 
> But, I am sure it not something you did

This problems is bc we need to make a seed of data

**Review by palomaquiroz — APPROVED** [review]

**Comment by sofpag** [comment]
@julianv97 
About the issues with Psychologists and Sessions... Valentin and I had some similar issues with ours resources. 
In my case, i resolved the issue of the edit function not showing the actual data, with this line of code in applications/form/index.js
`response.dateTime = response.dateTime.split('T')[0];`
 
So, as you know best, I will aprobe this PR

**Review by sofpag — APPROVED** [review]

**Comment by julianv97** [comment]
> @julianv97 About the issues with Psychologists and Sessions... Valentin and I had some similar issues with ours resources. In my case, i resolved the issue of the edit function not showing the actual data, with this line of code in applications/form/index.js `response.dateTime = response.dateTime.split('T')[0];`
> 
> So, as you know best, I will aprobe this PR

It's a problem on the backend, 
yesterday I did tests on this and I already know where the problem is

**Pull request merged**
